# Generated by Django 5.0.1 on 2024-02-08 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='Categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prd.category'),
        ),
    ]
